#!/usr/bin/bash
# Makes a request to 'https://pokeapi.co/api/v2/pokemon/25' and
# retrieves data for a specific Pokemon Pikachu

FILE='data.json'
URL='https://pokeapi.co/api/v2/pokemon/25'

if [ -f $FILE ]; then
    rm $FILE
else
    touch $FILE
fi

curl $URL > $FILE
