#!/usr/bin/bash
# Makes a request to 'https://pokeapi.co/api/v2/pokemon/25' and
# retrieves data for a specific Pokemon Pikachu

URL="https://pokeapi.co/api/v2/pokemon/25"
SUCCESS_FILE=$"data.json"
ERROR_FILE=$"errors.txt"

response=$(curl -s -w "%{http_code}" $URL)
http_code="${response: -3}"
body="${response%???}"

if [ "$http_code" -eq 200 ]; then
    echo "$body" > "$SUCCESS_FILE"
else
    echo "$body" > "$ERROR_FILE"
fi
