#!/usr/bin/bash
# Automates the retrival of data for multiple Pokemon and store in seperate files.

DIR="pokemon_data"
API_URL="https://pokeapi.co/api/v2/pokemon/"
POKEMONS=bulbasaur, ivysaur, venusaur, charmander, charmeleon"
ERROR_FILE="$DIR/errors.txt"

if [ ! -d "$DIR" ]; then
    mkdir -p "$DIR"
    touch "$ERROR_FILE"
fi

get_pokemon_data()
{
    local pokemon_name="$1"
    local file_path="$2"
    
    echo "Fetching data for $name_lower..."

    response=$(curl -s -w "%{http_code}" "$API_URL/$pokemon_name")
    http_code="${response: -3}"
    body="${response%???}"

    if [ "$http_code" -eq 200 ]; then
        echo "$body" > "$file_path"
        echo "Saved data to ${file_path} ✅"
    else
        echo "ERROR fetching $pokemon_name (code: $http_code)" | tee -a "$ERROR_FILE"
        echo "$body" >> "$ERROR_FILE"
    fi
}

IFS=',' read -ra TOKENS <<< "$POKEMONS"

for pokemon in "${TOKENS[@]}"; do
    pokemon=$(echo "$pokemon" | xargs)
    file_path=$(echo "$pokemon" | tr "A-Z" "a-z").json
    file_path="$DIR/$file_path"

    get_pokemon_data "$pokemon" "$file_path"

    sleep 1
done
