#!/usr/bin/bash
# Uses advanced text manipulation tools (jq, awk, and sed) to
# extract specific data from an API response.

set -euo pipefail

DATA_FILE="data.json"

name=$(jq -r .name $DATA_FILE | sed 's/.*/\u&/')
type=$(jq -r .types[].type.name $DATA_FILE | sed 's/.*/\u&/')
weight=$(jq -r .weight $DATA_FILE)
height=$(jq -r .height $DATA_FILE)

formatted_weight=$(echo $weight | awk '{printf "%d", $1}')
formatted_height=$(echo $height | awk '{printf "%.1f", $1/10}')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
