#!/usr/bin/bash
# Uses advanced text manipulation tools (jq, awk, and sed) to
# extract specific data from an API response.

set -euo pipefail

jq '{"name": .name, "type": .types[].type.name, "height": .height, "weight": .weight}' data.json |
    sed 's/[{}\,]/ /g; s/"//g; s/://g' |
    awk '\
    {
        for (i = 1; i <= NF; i++) {
            if ($i == "name") {
                name = toupper(substr($(i+1), 1, 1)) tolower(substr($(i+1), 2))
            }
            if ($i == "type") {
                type = toupper(substr($(i+1), 1, 1)) tolower(substr($(i+1), 2))
            }
            if ($i == "height")
                height = $(i+1)
            if ($i == "weight")
                weight = $(i+1)
        }
    }
    END {
        weight = weight / 10
        printf "%s is of type %s, weighs %skg, and is 0.%sm tall.\n", name, type, weight, height
    }'
